ble:
  device_name: WavePie
menu:
  items:
  - action_payload: a
    action_type: log
    label: 截图区域
  - action_payload: win+prtsc
    action_type: log
    label: 截全屏
  - action_payload: volume_down
    action_type: log
    label: 音量-
  - action_payload: ''
    action_type: log
    label: 新命令
  - action_payload: ''
    action_type: log
    label: 新命令
  - action_payload: ''
    action_type: log
    label: 新命令
