ble:
  device_name: WavePie
menu:
  items:
  - action_payload: win+e
    action_type: key_combo
    label: 资源管理器
  - action_payload: ctrl+z
    action_type: key_combo
    label: 撤销
  - action_payload: ctrl+s
    action_type: key_combo
    label: 保存
  - action_payload: ctrl+shift+z
    action_type: key_combo
    label: 重复
